version: "3"

networks:

  basecode:

    driver: bridge

services:

  basecode:

    networks:

      - basecode

    build:

      context: "./"
      dockerfile: "Dockerfile"
      args:

        TZ: "Asia/Jakarta"

        NODE_NAME: "basecode"
        NODE_ENV: "production"
        CENTER_START_PORT: "5000"
        CENTER_END_PORT: "5003"

    image: "basecode"
    container_name: "basecode"

    extra_hosts:

      - "localhost:0.0.0.0"

    ports:

      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "8000:8000"

    # entrypoint: [] #
    # command: ["tail", "-f", "/dev/null"] #

    healthcheck:

      test: curl --fail localhost:8000 || exit 1
      interval: 60s
      retries: 5
