# https://www.linkedin.com/pulse/docker-networking-anandan-ramadoss/?trk=public_profile_article_view #
# https://upcloud.com/resources/tutorials/load-balancing-docker-swarm-mode #

version: "3"

networks:

  basecode:

    driver: overlay

services:

  basecode:

    networks:

      - basecode

    image: "basecode"

    extra_hosts:

      - "localhost:0.0.0.0"

    ports:

      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "8000:8000"

    healthcheck:

      test: curl --fail localhost:8000 || exit 1
      interval: 60s
      retries: 5

    deploy:

      mode: replicated
      replicas: 4
      placement:

        constraints:

          - node.role==manager
